#!/bin/bash

echo "$PATH" > /tmp/eww-path.log
VAR_NAME="$1"

if [ -z "$VAR_NAME" ]; then
    echo "Usage: toggle-variable <variable_name>"
    exit 1
fi

CURRENT=$(~/.local/bin/eww get "$VAR_NAME")

if [ "$CURRENT" = "true" ]; then
    ~/.local/bin/eww update "$VAR_NAME=false"
else
    ~/.local/bin/eww update "$VAR_NAME=true"
fi
