#!/bin/bash

    count="$(dunstctl count history)"

    if [ $count -gt 0 ]; then
        col="#080808"
        bg="#bdbdbd"
        icon=""
    else
        bg="#080808"
        col="#bdbdbd"
        echo ""
    fi



    if [ "$(dunstctl is-paused)" == "true" ]; then
        icon=""
        col="#ff5d5d"
        bg="#080808"
    fi


if [ $1 = "notifs" ]; then
    echo $icon
elif [ $1 = "notifs_col" ]; then
    echo $col
elif [ $1 = "notifs_bg" ]; then
    echo $bg
elif [ $1 = "toggle_notifs" ]; then
    dunstctl set-paused toggle
fi
