#!/bin/bash

    if [ "$(systemctl status NetworkManager | grep 'inactive')" ]; then
        icon=""
        col="#ff5d5d"
        bg="#080808"
    fi
    
    if [ "$(nmcli g | grep -oE 'disconnected')" ]; then
        icon="" # disconnected
        col="#bdbdbd"
        bg="#080808"
    else
        icon="" # connected
        col="#080808"
        bg="#bdbdbd"
    fi


if [ $1 = "wifi" ]; then
    echo $icon
elif [ $1 = "wifi_col"  ]; then
    echo $col
elif [ $1 = "wifi_bg" ]; then
    echo $bg
fi
